version: '3'

services:
  backend:
    env_file:
        "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./DockerFile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./DockerFile
    ports:
      - "3000:3000"